// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: HomePanel

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label2;
extern void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TextArea1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

