// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: HomePanel

#include "ui.h"


// IMAGE DATA: assets/lvgl_test_image.png
lv_image_dsc_t ui_img_lvgl_test_image_png = {
    .header.w = 800,
    .header.h = 480,
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
};

void ui_img_lvgl_test_image_png_load()
{
    ui_img_lvgl_test_image_png.data = UI_LOAD_IMAGE("S:assets/ui_img_lvgl_test_image_png.bin", 1152000);
    ui_img_lvgl_test_image_png.data_size = 1152000;
}
