// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: HomePanel

#include "../ui.h"

lv_obj_t * uic_homebar;
lv_obj_t * uic_TextArea1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Background = NULL;
lv_obj_t * ui_Main_Window = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_Primary_Keyboard = NULL;
lv_obj_t * ui_homebar = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_Primary_Keyboard,  ui_TextArea1);
        _ui_state_modify(ui_Primary_Keyboard, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Primary_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_Primary_Keyboard,  ui_TextArea2);
        _ui_state_modify(ui_Primary_Keyboard, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Primary_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_TextArea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_Primary_Keyboard,  ui_TextArea3);
        _ui_state_modify(ui_Primary_Keyboard, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Primary_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Primary_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Primary_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_Primary_Keyboard, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Background = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Background, &ui_default_img);
    lv_obj_set_width(ui_Background, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Background, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Background, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_Window = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Main_Window);
    lv_obj_set_width(ui_Main_Window, 800);
    lv_obj_set_height(ui_Main_Window, 480);
    lv_obj_set_align(ui_Main_Window, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Main_Window, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Main_Window);
    lv_obj_set_width(ui_TextArea1, 244);
    lv_obj_set_height(ui_TextArea1, 70);
    lv_obj_set_x(ui_TextArea1, -260);
    lv_obj_set_y(ui_TextArea1, -150);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_TextArea2 = lv_textarea_create(ui_Main_Window);
    lv_obj_set_width(ui_TextArea2, 244);
    lv_obj_set_height(ui_TextArea2, 70);
    lv_obj_set_x(ui_TextArea2, 0);
    lv_obj_set_y(ui_TextArea2, -150);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");

    ui_TextArea3 = lv_textarea_create(ui_Main_Window);
    lv_obj_set_width(ui_TextArea3, 244);
    lv_obj_set_height(ui_TextArea3, 70);
    lv_obj_set_x(ui_TextArea3, 260);
    lv_obj_set_y(ui_TextArea3, -150);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");

    ui_Primary_Keyboard = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Primary_Keyboard, 791);
    lv_obj_set_height(ui_Primary_Keyboard, 251);
    lv_obj_set_x(ui_Primary_Keyboard, -1);
    lv_obj_set_y(ui_Primary_Keyboard, 110);
    lv_obj_set_align(ui_Primary_Keyboard, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Primary_Keyboard, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_Primary_Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_homebar = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_homebar);
    lv_obj_set_width(ui_homebar, 800);
    lv_obj_set_height(ui_homebar, 45);
    lv_obj_set_x(ui_homebar, 0);
    lv_obj_set_y(ui_homebar, -218);
    lv_obj_set_align(ui_homebar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_homebar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homebar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homebar, 75, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_homebar);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -342);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "HomePanel");

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Primary_Keyboard, ui_event_Primary_Keyboard, LV_EVENT_ALL, NULL);
    uic_TextArea1 = ui_TextArea1;
    uic_homebar = ui_homebar;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Background = NULL;
    ui_Main_Window = NULL;
    uic_TextArea1 = NULL;
    ui_TextArea1 = NULL;
    ui_TextArea2 = NULL;
    ui_TextArea3 = NULL;
    ui_Primary_Keyboard = NULL;
    uic_homebar = NULL;
    ui_homebar = NULL;
    ui_Label2 = NULL;

}
